### ISSUE TITLE
Incorrect units for timeout value

### ISSUE THREAD

**Issue by jfpanisset** [gfto/videohubctrl#5]
The `-t / --timeout` command line argument is defined as:

```
 -t --timeout <secs>        | Set connect/read timeout. Default: 15
```

This timeout value defaults to 15 and is clamped to between 0 and 60 in `parse_args()`, and is then passed to `fdread_ex()` which in turn passes it to `poll(2)`, but `poll(2)` defines its `timeout` argument in milliseconds, not in seconds. This causes problems on larger routers such as the Universal Videohub 288, where the default timeout value of 15 msec is not enough to allow the router to send its complete response, causing read_device_stream() to fail to parse an incomplete response from the router.

Fortunately the current maximum timeout value of 60 msec (`--timeout 60`) seems to be sufficient in my environment to read the complete response from the Videohub 288, but that's not very robust.

A couple of possible approaches to resolving this:

* change the documented definition of `-t / --timeout` to msec, increase the maximum accepted value to (say) 60,000 aka 60 seconds: this has the advantage of not changing the behavior of the application for existing scripts, while making it clear that the parameter is in msec rather than seconds
* keep the definition of `-t / --timeout` in seconds, multiply timeout by 1000 either when calling `fdread_ex()` or when calling `poll(2)` inside `fdread_ex()`: this changes the behavior of the application for existing scripts, but presumably a working setup doesn't rely on timeouts being exceeded, so multiplying the timeout value by 1,000 shouldn't break anything?

**Comment by gfto** [comment]
Should be fixed in https://github.com/gfto/videohubctrl/commit/46b46e9011ec7d54b7df4b620009a4666eb9c5d8
